name: "Build and Release"

on:
  # Triggers the workflow on push events to the "main" branch
  push:
    branches: ["main"]

  # Triggers the workflow on a Pull Request to the "main" branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build container
        run: |
          make build-docker
          make save-docker
  
  release:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Publish container
        run: |
          make load-docker
          make tag-docker DKR_IMG_SEMREL=ghcr.io/tarpanpathak/helloworld:${{ steps.semrel.outputs.version }}
          make login-docker DKR_REGISTRY_USER=${{ github.actor }} DKR_REGISTRY_TOKEN=${{ secrets.GH_TOKEN }}
          make push-docker DKR_IMG_SEMREL=ghcr.io/tarpanpathak/helloworld:${{ steps.semrel.outputs.version }}